# Generated by Django 3.2.6 on 2023-08-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='capacitacion_Actividad_leccion',
            fields=[
                ('id_actividadleccion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('descripcion', models.TextField()),
                ('url', models.TextField(blank=True, null=True)),
                ('orden_presentacion', models.SmallIntegerField(null=True)),
                ('peso_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('valor_elemento', models.TextField(blank=True, null=True)),
                ('fecha_disponibilidad', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_Actividad_Sesiones',
            fields=[
                ('id_capacitacionActividadSesiones', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('Descripción', models.TextField(null=True)),
                ('modalidad', models.CharField(choices=[('0', 'Presencial'), ('1', 'Online'), ('2', 'Mixta')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_Actividad_tareas',
            fields=[
                ('id_capacitacion_actividadTareas', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('Descripcion_tarea', models.TextField(null=True)),
                ('path_recurso', models.TextField(null=True)),
                ('tiempo_entrega', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_ActividadesTiempoReal',
            fields=[
                ('id_Actividad_tiempoReal', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_realizado', models.DateField(blank=True, null=True)),
                ('culminado', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_ActividadEvaluaciones',
            fields=[
                ('id_ActividadEvaluaciones', models.AutoField(primary_key=True, serialize=False)),
                ('nro_repeticiones', models.SmallIntegerField(null=True)),
                ('calificacion_aprobar', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duracion', models.SmallIntegerField(null=True)),
                ('point_in_use', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('titulo_evaluacion', models.TextField(null=True)),
                ('enviar_mensaje', models.CharField(choices=[('0', 'Mensaje'), ('1', 'Notificacion'), ('2', 'Ambas'), ('3', 'RRSS'), ('4', 'Telefono')], max_length=1)),
                ('enviar_notificacion_lider', models.CharField(choices=[('0', 'Mensaje'), ('1', 'Notificacion'), ('2', 'Ambas'), ('3', 'RRSS'), ('4', 'Telefono')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_ActSesiones_programar',
            fields=[
                ('id_capacitacionActSesiones_programar', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('datos_sesion', models.TextField(null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('duracion', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hora_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('recurrente', models.BooleanField(null=True)),
                ('datos_recurrencia', models.TextField(null=True)),
                ('Excepciones', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_Certificados',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_certificados', models.DateField(blank=True, null=True)),
                ('emitido', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_ComponentesActividades',
            fields=[
                ('id_componenteActividades', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('descripcion', models.TextField()),
                ('fecha_disponibilidad', models.DateField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('orden_presentacion', models.SmallIntegerField(null=True)),
                ('valor_elemento', models.TextField(blank=True, null=True)),
                ('peso_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_componentesPrerequisitos',
            fields=[
                ('id_componentePrerequisitos', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_componentesXestructura',
            fields=[
                ('id_componenteXestructura', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_EvaluacionesBloques',
            fields=[
                ('id_evaluacionesBloques', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo_bloque', models.TextField(null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tipo_bloque', models.CharField(choices=[('0', 'Normal'), ('1', 'Encuesta'), ('2', 'Experto'), ('3', 'Entrevista'), ('4', 'Logica')], max_length=1)),
                ('instrucciones_bloque', models.TextField(null=True)),
                ('valor_elemento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_EvaluacionesBloquesOpciones',
            fields=[
                ('id_EvaluacionesBloquesOpciones', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.TextField(null=True)),
                ('puntos_opcion', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_EvaluacionesPreguntas',
            fields=[
                ('id_capacitacionEvaluacionesPreguntas', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField(null=True)),
                ('path_imagen_pregunta', models.TextField(null=True)),
                ('puntos_pregunta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('orden', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_EvaluacionesPreguntasOpciones',
            fields=[
                ('id_capacitacionEvaluacionesPreguntasOpciones', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.TextField(null=True)),
                ('respuesta_correcta', models.BooleanField(null=True)),
                ('porc_respuesta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_Examenes',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('status_examen', models.CharField(choices=[('0', 'iniciado'), ('1', 'aprobado'), ('2', 'reprobado'), ('3', 'en revision')], max_length=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('nro_repeticiones', models.SmallIntegerField(null=True)),
                ('puntuacion_obtenida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.TextField(null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_ExamenesResultado',
            fields=[
                ('id_capacitacionExamenRespuestas', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_correcta', models.BooleanField(null=True)),
                ('puntos_obtenidos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respuesta_parrafo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_HistoricoActividades',
            fields=[
                ('id_historicoactvidades', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_lider', models.CharField(choices=[('0', 'por revisar '), ('1', 'cerrado')], max_length=1)),
                ('datos_resumen', models.TextField(null=True)),
                ('Comentarios_lider', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_LeccionPaginas',
            fields=[
                ('id_leccionPaginas', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('contenido', models.TextField(null=True)),
                ('orden_presentacion', models.SmallIntegerField(null=True)),
                ('id_recursos', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_NotificacionesMensajesXactividad',
            fields=[
                ('id_notiMenxactividad', models.AutoField(primary_key=True, serialize=False)),
                ('fk_actividad_componente', models.TextField(null=True)),
                ('tipo', models.CharField(choices=[('0', 'notificacion'), ('1', 'mensaje')], max_length=1)),
                ('cuando', models.CharField(choices=[('0', 'al inicio'), ('1', 'al finalizar ')], max_length=1)),
                ('fk_notificacionActividad', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_Recursos',
            fields=[
                ('id_recurso', models.SmallAutoField(primary_key=True, serialize=False)),
                ('path_rutas', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_SesionesRealizadas',
            fields=[
                ('pk_capacitacionSesionsesRealizadas', models.AutoField(primary_key=True, serialize=False)),
                ('tema_tratado', models.TextField(null=True)),
                ('comentario', models.TextField(null=True)),
                ('fecha_sesion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_Tag',
            fields=[
                ('id_tag', models.SmallAutoField(primary_key=True, serialize=False)),
                ('desc_tag', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_TagRecurso',
            fields=[
                ('id_tag_recurso', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='componentesFormacion',
            fields=[
                ('id_componetesformacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('descripcion', models.TextField()),
                ('codigo_componente', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('Fecha_activo', models.DateField(blank=True, null=True)),
                ('creditos_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('orden_presentacion', models.SmallIntegerField(null=True)),
                ('status_componente', models.IntegerField(blank=True, null=True)),
                ('tiene_certificad', models.BooleanField(null=True)),
                ('path_plantilla_certificado', models.TextField()),
                ('anno_semestre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EscalasEvaluaciones',
            fields=[
                ('id_escalaEvaluaciones', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(null=True)),
                ('maxima_puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estructuraprograma',
            fields=[
                ('id_estructura', models.SmallAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('Titulo', models.TextField(null=True)),
                ('valor_elemento', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('peso_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('orden_presentacion', models.SmallIntegerField(null=True)),
                ('fk_categoria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.conftablasconfiguracion')),
                ('fk_estructura_padre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.estructuraprograma')),
            ],
        ),
        migrations.CreateModel(
            name='EscalasCalificacion',
            fields=[
                ('id_escalaCalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True)),
                ('puntos_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fk_RangoCalificacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.conftablasconfiguracion')),
                ('fk_escalaEvaluaciones', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalaMenor', to='Capacitacion.escalasevaluaciones')),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion_tiempoxevaluaciones',
            fields=[
                ('id_tiempoxevaluaciones', models.AutoField(primary_key=True, serialize=False)),
                ('Desde', models.DateField(blank=True, null=True)),
                ('Hasta', models.DateField(blank=True, null=True)),
                ('fk_evaluacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_actividadevaluaciones')),
            ],
        ),
    ]
