# Generated by Django 3.2.6 on 2023-08-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizational_network', '0001_initial'),
        ('App', '0001_initial'),
        ('Capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion_tiempoxevaluaciones',
            name='fk_nodos',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_grupos'),
        ),
        migrations.AddField(
            model_name='capacitacion_tagrecurso',
            name='fk_recurso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Capacitacion.capacitacion_recursos'),
        ),
        migrations.AddField(
            model_name='capacitacion_tagrecurso',
            name='fk_tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Capacitacion.capacitacion_tag'),
        ),
        migrations.AddField(
            model_name='capacitacion_sesionesrealizadas',
            name='fk_sesionesProgramadas',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_actsesiones_programar'),
        ),
        migrations.AddField(
            model_name='capacitacion_sesionesrealizadas',
            name='fk_usuario_sesion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_actividadestiemporeal'),
        ),
        migrations.AddField(
            model_name='capacitacion_recursos',
            name='fk_tipoRecurso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_recurso', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_notificacionesmensajesxactividad',
            name='fk_tipoActividad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_leccionpaginas',
            name='fk_actividadLeccion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_actividad_leccion'),
        ),
        migrations.AddField(
            model_name='capacitacion_leccionpaginas',
            name='fk_statusPagina',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_status_pa', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_leccionpaginas',
            name='fk_tipoContenido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_contenido', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_historicoactividades',
            name='fk_componenteXestructura',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_componentesxestructura'),
        ),
        migrations.AddField(
            model_name='capacitacion_historicoactividades',
            name='fk_nodo_Grupo_integrantes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_gruposintegrantes'),
        ),
        migrations.AddField(
            model_name='capacitacion_examenesresultado',
            name='fk_capacitacionEvaluacionesPreguntasOpciones',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_evaluacionespreguntasopciones'),
        ),
        migrations.AddField(
            model_name='capacitacion_examenesresultado',
            name='fk_capacitacionExamenes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_examenes'),
        ),
        migrations.AddField(
            model_name='capacitacion_examenes',
            name='fk_ActividadEvaluaciones',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_actividadevaluaciones'),
        ),
        migrations.AddField(
            model_name='capacitacion_examenes',
            name='fk_nodo_Grupo_integrantes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_gruposintegrantes'),
        ),
        migrations.AddField(
            model_name='capacitacion_evaluacionespreguntasopciones',
            name='fk_capacitacionEvaluacionesPreguntas',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Capacitacion.capacitacion_evaluacionespreguntas'),
        ),
        migrations.AddField(
            model_name='capacitacion_evaluacionespreguntas',
            name='fk_evaluacionesBloques',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Capacitacion.capacitacion_evaluacionesbloques'),
        ),
        migrations.AddField(
            model_name='capacitacion_evaluacionespreguntas',
            name='fk_tipoPregunta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_evaluacionesbloquesopciones',
            name='fk_evaluacionesBloques',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Capacitacion.capacitacion_evaluacionesbloques'),
        ),
        migrations.AddField(
            model_name='capacitacion_evaluacionesbloques',
            name='fk_ActividadEvaluaciones',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Capacitacion.capacitacion_actividadevaluaciones'),
        ),
        migrations.AddField(
            model_name='capacitacion_evaluacionesbloques',
            name='fk_escalasEvaluaciones',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escala_evav', to='Capacitacion.escalasevaluaciones'),
        ),
        migrations.AddField(
            model_name='capacitacion_componentesxestructura',
            name='fk_componetesformacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.componentesformacion'),
        ),
        migrations.AddField(
            model_name='capacitacion_componentesxestructura',
            name='fk_estructuraprogramas',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.estructuraprograma'),
        ),
        migrations.AddField(
            model_name='capacitacion_componentesprerequisitos',
            name='fk_componenteActividades',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Capacitacion.capacitacion_componentesactividades'),
        ),
        migrations.AddField(
            model_name='capacitacion_componentesprerequisitos',
            name='fk_prerequisito',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisito', to='Capacitacion.capacitacion_componentesactividades'),
        ),
        migrations.AddField(
            model_name='capacitacion_componentesactividades',
            name='fk_componenteformacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.componentesformacion'),
        ),
        migrations.AddField(
            model_name='capacitacion_componentesactividades',
            name='fk_statuscomponente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_status', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_componentesactividades',
            name='fk_tipocomponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_componente', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_certificados',
            name='fk_componenteXestructuras',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_componentesxestructura'),
        ),
        migrations.AddField(
            model_name='capacitacion_certificados',
            name='fk_nodo_Grupo_integrantes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_gruposintegrantes'),
        ),
        migrations.AddField(
            model_name='capacitacion_actsesiones_programar',
            name='director_ponente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.apppublico'),
        ),
        migrations.AddField(
            model_name='capacitacion_actsesiones_programar',
            name='fk_grupoNodo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_grupos'),
        ),
        migrations.AddField(
            model_name='capacitacion_actsesiones_programar',
            name='gmt_horainternacional',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_hora_sesiones', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_actsesiones_programar',
            name='id_capacitacionActividadSesiones',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_actividad_sesiones'),
        ),
        migrations.AddField(
            model_name='capacitacion_actsesiones_programar',
            name='status_sesion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_sesiones', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividadevaluaciones',
            name='fk_componenteActividad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_atvidad_ev', to='Capacitacion.capacitacion_componentesactividades'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividadevaluaciones',
            name='fk_escalasEvaluaciones',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escala_ev', to='Capacitacion.escalasevaluaciones'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividadevaluaciones',
            name='fk_tipoduracion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividadestiemporeal',
            name='fk_componenteActividades',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_componentesactividades'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividadestiemporeal',
            name='fk_componenteXestructura',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_componentesxestructura'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividadestiemporeal',
            name='fk_nodo_Grupo_integrantes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_gruposintegrantes'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividad_tareas',
            name='fk_componenteActividad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_componentesactividades'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividad_tareas',
            name='fk_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_status_homework', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividad_tareas',
            name='fk_tipoTiempoEntrega',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_time', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividad_sesiones',
            name='fk_componenteActividad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_atvidad', to='Capacitacion.capacitacion_componentesactividades'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividad_sesiones',
            name='fk_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_status_sesiones', to='App.conftablasconfiguracion'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividad_leccion',
            name='fk_componenteActividad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.capacitacion_componentesactividades'),
        ),
        migrations.AddField(
            model_name='capacitacion_actividad_leccion',
            name='fk_statusleccion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_status_le', to='App.conftablasconfiguracion'),
        ),
    ]
