# Generated by Django 3.2.6 on 2023-08-25 15:19

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
        ('Capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin_Info',
            fields=[
                ('id_boletin', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contenido', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fech_inicio', models.DateField(blank=True, null=True)),
                ('fech_fin', models.DateField(blank=True, null=True)),
                ('path_recurso', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('requiere_accion', models.BooleanField()),
                ('url_accion', models.TextField()),
                ('status', models.BooleanField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Comunication_MsjPredeterminado',
            fields=[
                ('id_MSJ', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('url_link', models.TextField()),
                ('req_respuesta', models.BooleanField()),
                ('tipo_msj', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento_Post',
            fields=[
                ('id_post', models.SmallAutoField(primary_key=True, serialize=False)),
                ('link_post', models.TextField(blank=True, null=True)),
                ('orden', models.SmallIntegerField(null=True)),
                ('fk_escuela', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escuela', to='Capacitacion.estructuraprograma')),
                ('fk_modulo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modulo', to='Capacitacion.estructuraprograma')),
                ('fk_topico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Capacitacion.componentesformacion')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento_Post_Envio',
            fields=[
                ('id_PostEnvio', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tipo_receptor', models.TextField(blank=True, null=True)),
                ('tiempo_recordatorio', models.SmallIntegerField(null=True)),
                ('fk_post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Comunication.entrenamiento_post')),
                ('tipo_recordatorio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.conftablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento_Post_Envio_personas',
            fields=[
                ('id_post_envio_personas', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_envio', models.DateField(blank=True, null=True)),
                ('fecha_visto', models.DateField(blank=True, null=True)),
                ('marca', models.CharField(choices=[('0', 'Sin enviar'), ('1', 'Enviado'), ('2', 'Reenviado')], max_length=1)),
                ('fk_PostEnvio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Comunication.entrenamiento_post_envio')),
                ('fk_frecuencia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.conftablasconfiguracion')),
                ('fk_public', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.apppublico')),
            ],
        ),
    ]
