# Generated by Django 3.2.6 on 2023-08-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='helpingPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='tutoriales',
            fields=[
                ('idtutorial', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('url', models.TextField()),
                ('ordenamiento', models.SmallIntegerField()),
                ('modulo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modulo_ayuda', to='App.conftablasconfiguracion')),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_ayuda', to='App.conftablasconfiguracion')),
            ],
            options={
                'ordering': ['-idtutorial'],
            },
        ),
        migrations.CreateModel(
            name='paginas',
            fields=[
                ('idpagina', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('contenido', models.TextField()),
                ('url', models.TextField()),
                ('ordenamiento', models.SmallIntegerField(default=0)),
                ('fk_tutorial', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Helping.tutoriales')),
            ],
            options={
                'ordering': ['ordenamiento'],
            },
        ),
    ]
