# Generated by Django 3.2.6 on 2023-08-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
        ('Capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodos_grupos',
            fields=[
                ('if_gruponodo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
                ('valor_elemento', models.TextField()),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fk_grupoNodo_padre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_grupos')),
                ('fk_liderGrupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.apppublico')),
                ('status_grupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_status_nodo', to='App.conftablasconfiguracion')),
                ('ubicacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais', to='App.conftablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='nodos_PlanFormacion',
            fields=[
                ('idnodo_planformacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('orden_presentacion', models.SmallIntegerField(null=True)),
                ('fk_componentesXestructura', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forma', to='Capacitacion.capacitacion_componentesxestructura')),
                ('fk_gruponodo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_grupos')),
                ('fk_statusplan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_plan', to='App.conftablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='nodos_gruposIntegrantes',
            fields=[
                ('id_nodoGrupo_Integrantes', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fecha_incorporacion', models.DateField(blank=True, null=True)),
                ('datos_adicionales', models.TextField()),
                ('descripcion_comentarios', models.TextField()),
                ('fk_nodogrupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Organizational_network.nodos_grupos')),
                ('fk_public', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.apppublico')),
                ('motivo_desincorporacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='motivo', to='App.conftablasconfiguracion')),
                ('status_integrante', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_integrante', to='App.conftablasconfiguracion')),
            ],
        ),
    ]
