# Generated by Django 3.2.6 on 2023-08-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfMisfavoritos',
            fields=[
                ('idmisfavoritos', models.AutoField(primary_key=True, serialize=False)),
                ('idpublic', models.IntegerField()),
                ('direccion_url', models.TextField()),
                ('descripcion_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfSettings',
            fields=[
                ('idconfig_setting', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo_setting', models.TextField(db_column='Titulo_setting')),
                ('descripcion_setting', models.TextField(db_column='Descripcion_setting')),
            ],
        ),
        migrations.CreateModel(
            name='ConfTablasConfiguracion',
            fields=[
                ('id_tabla', models.SmallAutoField(primary_key=True, serialize=False)),
                ('desc_elemento', models.CharField(blank=True, max_length=350, null=True)),
                ('tipo_elemento', models.CharField(blank=True, max_length=1, null=True)),
                ('permite_cambios', models.IntegerField()),
                ('valor_elemento', models.TextField(blank=True, null=True)),
                ('mostrar_en_combos', models.IntegerField(blank=True, db_column='Mostrar_en_combos', null=True)),
                ('maneja_lista', models.IntegerField(blank=True, db_column='Maneja_lista', null=True)),
                ('datos_adicional', models.TextField(blank=True, db_column='Datos_adicional', null=True)),
                ('tipo_dato', models.SmallIntegerField(blank=True, db_column='Tipo_dato', null=True)),
                ('fk_tabla_padre', models.ForeignKey(db_column='fk_tabla_padre', on_delete=django.db.models.deletion.DO_NOTHING, to='App.conftablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='ConfSettings_Atributo',
            fields=[
                ('idconfig_atributo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Atributo', models.TextField(blank=True, db_column='atributo', null=True)),
                ('fecha_activo', models.DateField(blank=True, db_column='Fecha_activo', null=True)),
                ('status_setting', models.IntegerField(db_column='Status_setting')),
                ('rangovalor_setting', models.TextField(blank=True, db_column='RangoValor_setting', null=True)),
                ('valor_setting', models.TextField()),
                ('permite_borrar', models.IntegerField(db_column='Permite_Borrar')),
                ('fk_setting_padre', models.ForeignKey(db_column='fk_setting_padre', on_delete=django.db.models.deletion.DO_NOTHING, to='App.confsettings')),
                ('fk_tipo_dato_setting', models.ForeignKey(db_column='fk_Tipo_dato_setting', on_delete=django.db.models.deletion.DO_NOTHING, to='App.conftablasconfiguracion')),
            ],
        ),
        migrations.AddField(
            model_name='confsettings',
            name='fk_modulo_setting',
            field=models.ForeignKey(db_column='fk_modulo_setting', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.conftablasconfiguracion'),
        ),
        migrations.CreateModel(
            name='AppPublico',
            fields=[
                ('idpublico', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo_principal', models.TextField()),
                ('telefono_principal', models.TextField()),
                ('direccion', models.TextField()),
                ('telegram_id', models.TextField(blank=True, null=True)),
                ('pais', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.conftablasconfiguracion')),
            ],
        ),
    ]
